# Generated by Django 5.0.6 on 2024-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="количество товара"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_sell",
            field=models.BooleanField(
                default=True, verbose_name="Признак продажи товара"
            ),
        ),
    ]
