# Generated by Django 5.0.6 on 2024-06-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_count_product_is_sell"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="count",
        ),
    ]
